### ISSUE TITLE
🚀 Feature: Blog RSS feed meta tag

### ISSUE THREAD

**Issue by brittneypostma** [CodingCatDev/codingcat.dev#412]
### 🔖 Feature description

The site doesn't currently have a meta-tag for RSS readers to auto-detect the feed. We would need this meta-tag for each route an RSS feed exists on.

```html
<link 
  rel="alternate" 
  type="application/rss+xml" 
  title="RSS Feed for codingcat.dev" 
  href="/feed-blog.xml" 
/>
```

### 🎤 Pitch

Add meta-tag for RSS auto-detection

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/CodingCatDev/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by Bharadwajshivam28** [comment]
can i work on this
