### ISSUE TITLE
🚀 Feature: Account Details

### ISSUE THREAD

**Issue by codercatdev** [CodingCatDev/codingcat.dev#418]
### 🔖 Feature description

None Pro Currently
<img width="1492" alt="image" src="https://user-images.githubusercontent.com/3102249/231670651-0fbf1789-d5c7-4ac5-936d-2b90ee2f303c.png">

Pro 
<img width="1497" alt="image" src="https://user-images.githubusercontent.com/3102249/231670722-c6bfd09d-9f96-42f6-b782-e8cd48a5db87.png">

### 🎤 Pitch

Add something really nice, maybe like https://galaxies.dev/account

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/CodingCatDev/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by Bharadwajshivam28** [comment]
can i work on this issue

**Comment by mgehrls** [comment]
@Bharadwajshivam28 are you working on this? If not, I'm available as well.
