### ISSUE TITLE
🚀 Feature: Include Search Across Pages

### ISSUE THREAD

**Issue by codercatdev** [CodingCatDev/codingcat.dev#425]
### 🔖 Feature description

Add search, either with Algolia, Meilisearch or just in memory of some kind. 

### 🎤 Pitch

Add like the current.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/CodingCatDev/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by Bharadwajshivam28** [comment]
can i work on this issue

**Comment by codercatdev** [comment]
@Bharadwajshivam28 I have the search function working, we just need to clean up the result modal. I would love your help. Please don't hesitate with questions!!

[Screenshot_20230421-170126.png](https://user-images.githubusercontent.com/3102249/233734088-35da34aa-dc51-4738-aedb-9de75ee784a7.png)

**Comment by Bharadwajshivam28** [comment]
> @Bharadwajshivam28 I have the search function working, we just need to clean up the result modal. I would love your help. Please don't hesitate with questions!!
> 
> [Screenshot_20230421-170126.png](https://user-images.githubusercontent.com/3102249/233734088-35da34aa-dc51-4738-aedb-9de75ee784a7.png)
> 
> 

Okay thanks

**Comment by Bharadwajshivam28** [comment]
> @Bharadwajshivam28 I have the search function working, we just need to clean up the result modal. I would love your help. Please don't hesitate with questions!!
> 
> [Screenshot_20230421-170126.png](https://user-images.githubusercontent.com/3102249/233734088-35da34aa-dc51-4738-aedb-9de75ee784a7.png)
> 
> 

I got your point but can you just elaborate it more in simple words

**Comment by Bharadwajshivam28** [comment]
okay

**Comment by codercatdev** [comment]
Hey @Bharadwajshivam28 I added the logos in a new PR.

**Comment by Bharadwajshivam28** [comment]
> Hey @Bharadwajshivam28 I added the logos in a new PR #437 437

Okay...
