### ISSUE TITLE
🐛 Bug Report: 

### ISSUE THREAD

**Issue by Bharadwajshivam28** [CodingCatDev/codingcat.dev#431]
### 👟 Reproduction steps

I found it while exploring the page

### 👍 Expected behavior

It should either give the next page or button next should be removed  

### 👎 Actual Behavior

In the Tutorials section when we scroll down and click on next button then we get a error. We can fix it or if there is no  more page then we can remove the next button from the tutorials section

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/CodingCatDev/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by codercatdev** [comment]
resolved
