### ISSUE TITLE
Fly.io with Dov Alperin

### ISSUE THREAD

**Issue by codercatdev** [CodingCatDev/codingcat.dev#505]
Booked for Mon Nov 13, 2023 2pm - 3pm

- [x] cover image @codercatdev 
- [ ] purrfect picks @codercatdev
- [ ] purrfect picks @brittneypostma 
- [x] streamyard updated on meeting @codercatdev 
- [x] podcast edited @ahmulder 
- [ ] podcast live: youtube @ahmulder 
- [ ] podcast live: spotify @ahmulder 
- [ ] post update: slug @ahmulder 
- [ ] post update: youtube @ahmulder 
- [ ] post update: spotify @ahmulder 
- [ ] review site @brittneypostma 
- [ ] pr merge @codercatdev or @brittneypostma

**Comment by codercatdev** [comment]
Topic Ideas

- Background on you and how you got to fly.

- What is Replication and Deployment at Global Scale?
- Why do CDN's exist, and what does that have to do with my single Docker file?
- I am used to CloudRun, I think you are using [Firecracker](https://github.com/firecracker-microvm/firecracker), how does an image turn into a true VM?
- How does it handle the VPC side of different applications running in your organization?
- Should you use [Postgres](https://fly.io/docs/postgres/) for more than just development?
- Does it make sense to host something like [Next.js](https://fly.io/docs/js/frameworks/nextjs/) or should this still be handled by [Vercel](https://vercel.com/) or [Netlify](https://www.netlify.com/)

**Comment by codercatdev** [comment]
Alex's Pick

https://blog.sentry.io/performance-monitoring-for-every-developer-web-vitals-and-function/?original_referrer=https%3A%2F%2Fsentry.io%2F

**Comment by DAlperin** [comment]
https://fly.io/blog/docker-without-docker/

**Comment by DAlperin** [comment]
https://fly.io/docs/reference/private-networking/

https://fly.io/blog/flydotio-heart-bun/ (image inside)

**Comment by codercatdev** [comment]
Additional Links to add

https://github.com/epicweb-dev/epic-stack
https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/
https://github.com/fly-apps/bun

**Comment by codercatdev** [comment]
Dov's pick
https://tv.apple.com/us/show/the-morning-show/umc.cmc.25tn3v8ku4b39tr6ccgb8nl6m

**Comment by codercatdev** [comment]
Hey @ahmulder here is the recording
https://drive.google.com/open?id=1imKAx9xiPV9-QzxUKCIlxWDOTio1DuFr&usp=drive_fs

This will be 3.22
