### ISSUE TITLE
TypeScript is freaking hard with Richard Bray

### ISSUE THREAD

**Issue by codercatdev** [CodingCatDev/codingcat.dev#523]
Dec 4, 2023 9am ET

- [x] cover image @codercatdev 
- [ ] streamyard updated on meeting @codercatdev 
- [ ] purrfect picks @codercatdev
- [ ] purrfect picks @brittneypostma 
- [ ] podcast edited @ahmulder 
- [ ] podcast live: youtube @ahmulder 
- [ ] podcast live: spotify @ahmulder 
- [ ] post update: slug @ahmulder 
- [ ] post update: youtube @ahmulder 
- [ ] post update: spotify @ahmulder 
- [ ] review site @brittneypostma 
- [ ] pr merge @codercatdev or @brittneypostma

**Comment by codercatdev** [comment]
@RichardBray 

Here is the preview: https://codingcat-dev-git-feature-523-typescript-bas-ceead8-codercatdev.vercel.app/podcast/_typescript-is-freaking-hard


Here is yoru profile page: https://codingcat-dev-git-feature-523-typescript-bas-ceead8-codercatdev.vercel.app/guest/richard-bray

**Comment by RichardBray** [comment]
Hey @CodingCatDev/codingcat-dev thanks for sharing this. I thought the plan was to talk about Phaser 😅

We can do Typescript but I think it might be a short podcast if we just focused on that 😁

**Comment by codercatdev** [comment]
@RichardBray I feel like there is so much there. Based on all your shorts you are putting out I thought you were diving into more of that. I am happy to switch it up though :D

**Comment by RichardBray** [comment]
Ha sounds like you have a good plan. I thought it was going to be a show just about TypeScript but if it's not then it should be fine 😅

**Comment by codercatdev** [comment]
Purrfect Picks

Alex - https://tv.apple.com/us/show/slow-horses/umc.cmc.2szz3fdt71tl1ulnbp8utgq5o?mttn3pid=Google%20AdWords&mttnagencyid=a5e&mttncc=US&mttnsiteid=143238&mttnsubad=OUS2019944_1-679292938313-c&mttnsubkw=137832448950__yPtoHWQj_&mttnsubplmnt=_adext_
Richard - https://www.pawpatrol.movie/home/
Brittney - https://www.yardhouse.com/menu/poke-nachos/prod2950052
