### ISSUE TITLE
Compassionate Coding: Emotional Intelligence for Engineers

### ISSUE THREAD

**Issue by codercatdev** [CodingCatDev/codingcat.dev#537]
- [x] cover image @codercatdev 
- [ ] purrfect picks @codercatdev
- [ ] purrfect picks @brittneypostma 
- [x] streamyard updated on meeting @codercatdev 
- [ ] podcast edited @ahmulder 
- [ ] podcast live: youtube @ahmulder 
- [ ] podcast live: spotify @ahmulder 
- [ ] post update: slug @ahmulder 
- [ ] post update: youtube @ahmulder 
- [ ] post update: spotify @ahmulder 
- [ ] review site @brittneypostma 
- [ ] pr merge @codercatdev or @brittneypostma

**Comment by codercatdev** [comment]
https://compassionatecoding.com/

Dec 5, 2023 ⋅ 3pm – 4pm

**Comment by codercatdev** [comment]
@aprilw here is the draft

Preview:
https://codingcat-dev-git-537-compassionate-coding-e-5c088f-codercatdev.vercel.app/podcast/_compassionate-coding

Profile:
https://codingcat-dev-git-537-compassionate-coding-e-5c088f-codercatdev.vercel.app/guest/april-wensel

**Comment by aprilw** [comment]
Looks great, thanks! Looking forward to it. 🎙️

**Comment by codercatdev** [comment]
Alex Purrfect Pick: Monarch Legacy of Monsters 
https://tv.apple.com/us/show/monarch-legacy-of-monsters/umc.cmc.62l8x0ixrhyq3yaqa5y8yo7ew

**Comment by codercatdev** [comment]
LInks:

Self Compassion-
https://www.amazon.com/s?k=self+compassion+kristin+neff&hvadid=598610969016&hvdev=c&hvlocphy=9017490&hvnetw=g&hvqmt=e&hvrand=10318612918484662336&hvtargid=kwd-30489409529&hydadcr=15528_13558556&tag=googhydr-20&ref=pd_sl_4zu2ziyg0i_e
