### ISSUE TITLE
Refine with Batuhan Ozdemir

### ISSUE THREAD

**Issue by ashleycodingcat** [CodingCatDev/codingcat.dev#564]
12pm-1:30pm ET

Photo URL
[https://avatars.githubusercontent.com/u/16444991?v=4](https://www.google.com/url?q=https%3A%2F%2Favatars.githubusercontent.com%2Fu%2F16444991%3Fv%3D4&sa=D&ust=1702213560000000&usg=AOvVaw1_URNtUuxkqLK_bT0PTIDm)

GitHub URL
[https://github.com/BatuhanW](https://www.google.com/url?q=https%3A%2F%2Fgithub.com%2FBatuhanW&sa=D&ust=1702213560000000&usg=AOvVaw3F6Kz1DPy7OjCJ0zFCQz0e)

X URL (Twitter)
[https://twitter.com/kakamelatte](https://www.google.com/url?q=https%3A%2F%2Ftwitter.com%2Fkakamelatte&sa=D&ust=1702213560000000&usg=AOvVaw3z1tZeR_GZKq5jxecEvG-N)

Subject
Refine

Every Week, Alex pair programs with the brightest minds in web development to learn something new in 90 minutes.

 Rough schedule:First 30 minutes is us chatting and the audience learning more about you.Last 60 minutes is us pair-programming to create / learn a specific subject.

[https://beacons.ai/codingcatdev](https://www.google.com/url?q=https%3A%2F%2Fbeacons.ai%2Fcodingcatdev&sa=D&ust=1702213560000000&usg=AOvVaw0fkDVNaW-XfaHS7FO-2A3U)

**Comment by codercatdev** [comment]
Links: 

https://github.com/refinedev/coding-cat-demo
https://refine.dev/docs/guides-concepts/contributing/
https://example.crm.refine.dev/scrumboard/kanban
https://github.com/refinedev/refine/issues
